USE [master]
GO

/****** Object:  Database [OnlineDevDb]    Script Date: 17.02.2021 21:43:12 ******/
CREATE DATABASE [OnlineDevDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'OnlineDevDb', FILENAME = N'E:\Asp.Net Mvc Denemeler\OnlineDevamsizlik\db\OnlineDevDb.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'OnlineDevDb_log', FILENAME = N'E:\Asp.Net Mvc Denemeler\OnlineDevamsizlik\db\OnlineDevDb_log.ldf' , SIZE = 2048KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [OnlineDevDb] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [OnlineDevDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [OnlineDevDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [OnlineDevDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [OnlineDevDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [OnlineDevDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [OnlineDevDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [OnlineDevDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [OnlineDevDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [OnlineDevDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [OnlineDevDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [OnlineDevDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [OnlineDevDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [OnlineDevDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [OnlineDevDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [OnlineDevDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [OnlineDevDb] SET  DISABLE_BROKER 
GO

ALTER DATABASE [OnlineDevDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [OnlineDevDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [OnlineDevDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [OnlineDevDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [OnlineDevDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [OnlineDevDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [OnlineDevDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [OnlineDevDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [OnlineDevDb] SET  MULTI_USER 
GO

ALTER DATABASE [OnlineDevDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [OnlineDevDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [OnlineDevDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [OnlineDevDb] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [OnlineDevDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [OnlineDevDb] SET  READ_WRITE 
GO


