//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OD.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OnlineDevDbEntities : DbContext
    {
        public OnlineDevDbEntities()
            : base("name=OnlineDevDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DersGruplari> DersGruplari { get; set; }
        public virtual DbSet<ilceler> ilceler { get; set; }
        public virtual DbSet<iller> iller { get; set; }
        public virtual DbSet<Ogrenciler> Ogrenciler { get; set; }
        public virtual DbSet<Talepler> Talepler { get; set; }
        public virtual DbSet<OgretmenLog> OgretmenLog { get; set; }
        public virtual DbSet<OkulLog> OkulLog { get; set; }
        public virtual DbSet<AdminLog> AdminLog { get; set; }
        public virtual DbSet<AdminTBL> AdminTBL { get; set; }
        public virtual DbSet<Donemler> Donemler { get; set; }
        public virtual DbSet<Ogretmenler> Ogretmenler { get; set; }
        public virtual DbSet<Okullar> Okullar { get; set; }
        public virtual DbSet<Dersler> Dersler { get; set; }
        public virtual DbSet<AtananDersler> AtananDersler { get; set; }
        public virtual DbSet<Yoklamalar> Yoklamalar { get; set; }
    }
}
