//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OgretmenLog
    {
        public int OgretmenLogID { get; set; }
        public string ActionName { get; set; }
        public string ControllerName { get; set; }
        public string IPAddress { get; set; }
        public string Url { get; set; }
        public Nullable<int> OgretmenID { get; set; }
        public string ExecutionMs { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    
        public virtual Ogretmenler Ogretmenler { get; set; }
    }
}
