//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yoklamalar
    {
        public int YoklamaID { get; set; }
        public Nullable<int> OgretmenID { get; set; }
        public string OgrenciIDListe { get; set; }
        public Nullable<int> DersID { get; set; }
        public Nullable<int> DersGrupID { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> DonemID { get; set; }
        public Nullable<bool> AktifMi { get; set; }
        public Nullable<int> OkulID { get; set; }
        public Nullable<int> Sinif { get; set; }
        public string Sube { get; set; }
    
        public virtual DersGruplari DersGruplari { get; set; }
        public virtual Dersler Dersler { get; set; }
        public virtual Donemler Donemler { get; set; }
        public virtual Ogretmenler Ogretmenler { get; set; }
        public virtual Okullar Okullar { get; set; }
    }
}
